### ISSUE TITLE
Jint version != 2.9.1 FileLoadException

### ISSUE THREAD

**Issue by thizzo** [SimonCropp/Strike#11]
Hi, i recently wanted to use this library. But had some difficulties with the dependencie library jint.

If i install any other version of Jint than 2.9.1 i will get the following exception:

System.IO.FileLoadException : Could not load file or assembly 'Jint, Version=2.9.1.0, Culture=neutral, PublicKeyToken=2e92ba9c8d81157f' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at Strike.Jint.Markdownify..ctor(Options options, RenderMethods rendereMethods)

Strike.Jint nuspec says Jint version from 2.9.0 until version lesser than 3.0.0 is supported. Am i missing something or is the nuspec wrong?

best regards thizzo

**Comment by SimonCropp** [comment]
Jing is strong named. So u need to add a binding redirect
