### ISSUE TITLE
https://github.com/SimonCropp/Strike/issues/new

### ISSUE THREAD

**Issue by qujck** [SimonCropp/Strike#4]
Hi,

I'm not sure where this question belongs so I'm starting here.

I've got (hacked together) google prettify into the mix with one line of code

```csharp
string markdown = transformer.Transform(content);
markdown = markdown.Replace("<pre", "<pre class=\"prettyprint\"");
```

But it is not working for all flavours. 

`'''csharp` works in so much that I get `<pre class="prettyprint"><code class="lang-csharp">` in the html but `'''none` does not give me `<pre class="prettyprint"><code class="lang-none">`, it instead outputs as `<pre class="prettyprint"><code>`

(I'm trying to output a DOS batch file)

Is there a built in way of integrating google prettify into the pipeline?

**Comment by SimonCropp** [comment]
think this should be raised here https://github.com/chjj/marked/
