### ISSUE TITLE
Expose text renderer

### ISSUE THREAD

**Issue by synhershko** [SimonCropp/Strike#5]
See https://github.com/chjj/marked/pull/569

**Comment by SimonCropp** [comment]
R u sure u want supports for an unreleased feature?

**Comment by SimonCropp** [comment]
how about i release a beta with support for this?

**Comment by synhershko** [comment]
I can wait. Not sure when they'll release though, marked.js is not really maintained anymore

**Comment by SimonCropp** [comment]
actually it seems to have had a jumpstart https://github.com/chjj/marked/commits/master

**Comment by synhershko** [comment]
Nah looks like a PR merging spree, been there done that :)

**Comment by SimonCropp** [comment]
try https://www.nuget.org/packages/Strike.IE/1.2.0-beta01
