### ISSUE TITLE
.NET Framework 4.5 vs 4.5.2

### ISSUE THREAD

**Issue by dirkrombauts** [SimonCropp/Strike#9]
I noticed that you compile the Strike libraries against version 4.5.2 of the .NET Framework. I am maintaining a 4.5 project where I would like to use Strike through Nuget. Is there any reason for using 4.5.2, or was it just the default version of the framework at the time?

If you are interested, I will send you a PR with all the projects set to compile again version 4.5

**Comment by SimonCropp** [comment]
given 4.5.2 is 2.5 years old i would assume that is "supporting old enough" versions. is there something blocking you from updating to 4.5.2?

**Comment by dirkrombauts** [comment]
Yes ... I'm the maintainer of [Pickles](https://github.com/picklesdoc/pickles), which is often used in corporate environments. Corporate environments are often *very* slow in updating their .NET frameworks.

So I would really prefer to remain on 4.5 and be able to get Strike from Nuget.

**Comment by SimonCropp** [comment]
ok. how about i make u an owner of the projects and the nuget?

**Comment by dirkrombauts** [comment]
Fine by me (although I think that's overkill :-) )  I use dirk dot rombauts at questmaster dot net for Nuget and GitHub both.

**Comment by SimonCropp** [comment]
r u on appveyor?

**Comment by dirkrombauts** [comment]
yes I am

**Comment by dirkrombauts** [comment]
Quick question: where do I set the nuget package version? I'm assuming there's some sort of global variable that I can increment from 1.8.0 to 1.9.0.

**Comment by SimonCropp** [comment]
It is inferred from the assembly version

**Comment by dirkrombauts** [comment]
Could you please check whether I have access to the Strike.IE.Merged and Strike.V8 projects on nuget? The other three work fine.

**Comment by SimonCropp** [comment]
says u r a pending owner 
![image](https://cloud.githubusercontent.com/assets/122666/20904856/8751b506-bb95-11e6-8502-d3fbf0f5efed.png)

**Comment by SimonCropp** [comment]
perhaps check your older email?

want me to push in the short term? until u get it sorted?

**Comment by dirkrombauts** [comment]
I check older email and various spam folders but no luck. Could you perhaps try to remove and re-add me to those two projects? Many thanks!

**Comment by SimonCropp** [comment]
removed and re-added. if that doesnt work i think we should contact nuget support

**Comment by dirkrombauts** [comment]
I received an invitation for Strike.IE.Merged, and was able to accept it.

I did not receive an invitation for Strike.V8. Did you re-send one?

**Comment by SimonCropp** [comment]
removed and re-added a 3rd time :)

**Comment by dirkrombauts** [comment]
No luck ... I'll contact nuget support.

You know, I think it's weird that there's no page or tab in the nuget account settings that list pending invitations ...

**Comment by dirkrombauts** [comment]
I heard back rom support. They are investigating. In the meantime, they ask that we try one more time "to see if it was maybe a point in time issue with the service".

**Comment by dirkrombauts** [comment]
Thanks for releasing a new version - could you perhaps try one more time to add me to the Strike.V8 project on nuget?

**Comment by SimonCropp** [comment]
sorry this dropped off my radar

i cant try to add u again since u have a pending approval. and it wont let me remove your pending approval either

![image](https://user-images.githubusercontent.com/122666/35798285-70356914-0ab6-11e8-8fe9-38921f74a279.png)

**Comment by dirkrombauts** [comment]
No idea what might be going on. I don't see any invitations on my side. Maybe you can ask support?

**Comment by SimonCropp** [comment]
didnt u already try asking support?
